---
title: "Gapminder Exercise Template"
author: "Andrew Cooper"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 7)
```


## Load packages

```{r message=FALSE}
library(tidyverse)
```

## Load data

```{r}
gap <- read_csv("https://bit.ly/gap_data_upd")

```

## Exercises

### Exercise 1

How many observations are in this dataset?

```{r nrow, echo=F}
num_rows <- nrow(gap)
```

There are ``r num_rows`` observations in the dataset.

### Exercise 2

Visualize the relationship between GDP and life expectancy for 
countries in Europe in 1952 using a scatter plot.

```{r eu_52, echo=F}
eu_1952 <- gap %>%
  filter(continent == "Europe", year==1952)

ggplot(data=eu_1952, aes(x=gdpPercap,y=lifeExp)) + geom_point()
```

### Exercise 3

Add year 1967 in another color.

```{r eu_52_67, echo=F}
eu_52_67 <- gap %>%
  filter(continent=="Europe", year %in% c(1952,1967))
ggplot(data=eu_52_67, aes(x=gdpPercap,y=lifeExp,col=factor(year))) + geom_point()
```

